#!/usr/bin/env node

/**
 * generate-latex.mjs — Validate and compile a generated .tex CV file to PDF
 *
 * Usage:
 *   node generate-latex.mjs <input.tex> [output.pdf]
 *
 * Reads the .tex file, validates structure, compiles to PDF via tectonic or pdflatex.
 * If output.pdf is omitted, writes to the same directory as input with .pdf extension.
 * The .tex file is generated by the AI agent using templates/cv-template.tex.
 *
 * Requires: tectonic (preferred, brew install tectonic) or pdflatex (MiKTeX / TeX Live) on PATH.
 */

import { readFile, writeFile, stat, copyFile, rm, mkdtemp } from 'fs/promises';
import { resolve, basename, dirname, join } from 'path';
import { execFileSync } from 'child_process';
import { existsSync, mkdirSync } from 'fs';
import { tmpdir } from 'os';

const REQUIRED_SECTIONS = [
  '\\\\section{Education}',
  '\\\\section{Work Experience}',
  '\\\\section{Personal Projects}',
  '\\\\section{Technical Skills}',
];

const REQUIRED_COMMANDS = [
  '\\\\resumeSubheading',
  '\\\\resumeItem',
  '\\\\resumeProjectHeading',
];

const FORBIDDEN_TEX_PATTERNS = [
  /\\write18\b/i,
  /\\openout\b/i,
  /\\openin\b/i,
  /\\read\b/i,
  /\\immediate\s*\\write\b/i,
  /\\usepackage\{shellesc\}/i,
  /\\(?:lstinputlisting|VerbatimInput|IfFileExists|InputIfFileExists)\b/i,
];

async function main() {
  const inputPath = process.argv[2];
  const outputPath = process.argv[3]; // optional
  if (!inputPath) {
    console.error('Usage: node generate-latex.mjs <input.tex> [output.pdf]');
    process.exit(1);
  }

  const absPath = resolve(inputPath);
  let content;
  try {
    content = await readFile(absPath, 'utf-8');
  } catch (err) {
    console.error(`Error reading ${absPath}: ${err.message}`);
    process.exit(1);
  }

  const issues = [];

  // Check required sections
  for (const pattern of REQUIRED_SECTIONS) {
    if (!new RegExp(pattern).test(content)) {
      issues.push(`Missing section matching: ${pattern}`);
    }
  }

  // Check required commands are used
  for (const cmd of REQUIRED_COMMANDS) {
    if (!new RegExp(cmd).test(content)) {
      issues.push(`Missing command: ${cmd}`);
    }
  }

  // Check document structure
  if (!content.includes('\\begin{document}')) {
    issues.push('Missing \\begin{document}');
  }
  if (!content.includes('\\end{document}')) {
    issues.push('Missing \\end{document}');
  }

  // Check for unresolved placeholders
  const unresolvedMatch = content.match(/\{\{[A-Z_]+\}\}/g);
  if (unresolvedMatch) {
    issues.push(`Unresolved placeholders: ${[...new Set(unresolvedMatch)].join(', ')}`);
  }

  for (const pattern of FORBIDDEN_TEX_PATTERNS) {
    if (pattern.test(content)) {
      issues.push(`Unsafe TeX primitive blocked: ${pattern}`);
    }
  }

  for (const match of content.matchAll(/\\(?:input|include)\{([^}]+)\}/g)) {
    const includeTarget = String(match[1] || '').trim();
    if (!includeTarget) continue;
    const allowList = new Set(['glyphtounicode']);
    if (allowList.has(includeTarget.replace(/\.tex$/i, ''))) continue;
    if (includeTarget.startsWith('/') || includeTarget.includes('..') || includeTarget.startsWith('|')) {
      issues.push(`Unsafe include path blocked: ${includeTarget}`);
    }
  }

  // Check for common unescaped special chars in text (heuristic)
  const lines = content.split('\n');
  let resumeItemCount = 0;
  let subheadingCount = 0;
  let projectHeadingCount = 0;

  for (const line of lines) {
    if (/\\resumeItem\{/.test(line)) resumeItemCount++;
    if (/\\resumeSubheading[^C]/.test(line)) subheadingCount++;
    if (/\\resumeProjectHeading/.test(line)) projectHeadingCount++;
  }

  // Check pdfgentounicode
  if (!content.includes('\\pdfgentounicode=1')) {
    issues.push('Missing \\pdfgentounicode=1 (ATS compatibility)');
  }

  const fileInfo = await stat(absPath);
  const sizeKB = (fileInfo.size / 1024).toFixed(1);

  // Output report as JSON
  const report = {
    file: basename(absPath),
    path: absPath,
    sizeKB: parseFloat(sizeKB),
    counts: {
      resumeItems: resumeItemCount,
      subheadings: subheadingCount,
      projectHeadings: projectHeadingCount,
    },
    issues,
    valid: issues.length === 0,
  };

  // If validation fails, report and exit
  if (issues.length > 0) {
    console.log(JSON.stringify(report, null, 2));
    process.exit(1);
  }

  // --- Compile .tex → .pdf ---
  const texDir = dirname(absPath);
  const texBase = basename(absPath, '.tex');
  const defaultPdf = join(texDir, `${texBase}.pdf`);
  const targetPdf = outputPath ? resolve(outputPath) : defaultPdf;
  let compileDir;
  try {
    compileDir = await mkdtemp(join(tmpdir(), 'yocareer-tex-'));
  } catch (err) {
    report.compiled = false;
    report.compileError = `mkdtemp failed: ${err.message}`;
    console.log(JSON.stringify(report, null, 2));
    process.exit(1);
  }

  // Ensure output directory exists
  const targetDir = dirname(targetPdf);
  if (!existsSync(targetDir)) {
    mkdirSync(targetDir, { recursive: true });
  }

  // Detect available engines
  const availableEngines = [];
  for (const candidate of ['tectonic', 'pdflatex', 'xelatex']) {
    try {
      execFileSync(candidate, ['--version'], { stdio: 'pipe' });
      availableEngines.push(candidate);
    } catch { /* not found */ }
  }

  // Check if the document declares a specific engine (e.g., CJK documents need xelatex)
  const requiresXelatex = content.includes('% !TeX program = xelatex');
  let engine = null;

  if (requiresXelatex) {
    if (availableEngines.includes('xelatex')) {
      engine = 'xelatex';
    } else {
      report.compiled = false;
      report.compileError = 'This document requires xelatex for CJK support, but xelatex is not installed.';
      console.log(JSON.stringify(report, null, 2));
      process.exit(1);
    }
  } else {
    // Default priority: tectonic > pdflatex
    engine = availableEngines.find(e => e === 'tectonic' || e === 'pdflatex') || availableEngines[0];
  }

  if (!engine) {
    report.compiled = false;
    report.compileError = 'No LaTeX engine found. Install tectonic (brew install tectonic), pdflatex, or xelatex.';
    console.log(JSON.stringify(report, null, 2));
    process.exit(1);
  }

  report.engine = engine;

  // Compile from an isolated temp directory to avoid arbitrary local-file reads.
  let compileContent = content;
  if (engine === 'tectonic') {
    compileContent = compileContent
      .replace(/\\pdfgentounicode\s*=\s*\d+[^\n]*\n?/g, '')
      .replace(/\\input\{glyphtounicode\}[^\n]*\n?/g, '');
  }
  const compilePath = join(compileDir, `${texBase}.tex`);
  await writeFile(compilePath, compileContent, 'utf-8');

  try {
    if (engine === 'tectonic') {
      // Tectonic handles multi-pass automatically; --untrusted hardens parser behavior.
      execFileSync('tectonic', ['--untrusted', '--outdir', compileDir, compilePath], {
        cwd: compileDir,
        stdio: 'pipe',
        timeout: 120_000,
      });
    } else if (engine === 'pdflatex') {
      const pdflatexArgs = [
        '-no-shell-escape',
        '-interaction=nonstopmode',
        '-halt-on-error',
        `-output-directory=${compileDir}`,
        compilePath,
      ];
      // First pass
      execFileSync('pdflatex', pdflatexArgs, { cwd: compileDir, stdio: 'pipe', timeout: 120_000 });
      // Second pass (resolves references)
      execFileSync('pdflatex', pdflatexArgs, { cwd: compileDir, stdio: 'pipe', timeout: 120_000 });
    } else if (engine === 'xelatex') {
      const xelatexArgs = [
        '-no-shell-escape',
        '-interaction=nonstopmode',
        '-halt-on-error',
        `-output-directory=${compileDir}`,
        compilePath,
      ];
      // First pass
      execFileSync('xelatex', xelatexArgs, { cwd: compileDir, stdio: 'pipe', timeout: 120_000 });
      // Second pass (resolves references)
      execFileSync('xelatex', xelatexArgs, { cwd: compileDir, stdio: 'pipe', timeout: 120_000 });
    }

    report.compiled = true;
  } catch (err) {
    const logPath = join(compileDir, `${texBase}.log`);
    let latexError = err.message;
    try {
      const log = await readFile(logPath, 'utf-8');
      const errorLines = log.split('\n').filter(l => l.startsWith('!'));
      if (errorLines.length > 0) {
        latexError = errorLines.join('\n');
      }
    } catch { /* no log file */ }

    report.compiled = false;
    report.compileError = latexError;
  }

  // Post-compile: move PDF and clean up (separate from compile errors)
  if (report.compiled) {
    const compileBase = basename(compilePath, '.tex');
    const compiledPdf = join(compileDir, `${compileBase}.pdf`);

    try {
      await copyFile(compiledPdf, targetPdf);
      if (resolve(compiledPdf) !== resolve(targetPdf)) {
        await rm(compiledPdf).catch(() => {});
      }

      const pdfStat = await stat(targetPdf);
      report.pdf = {
        path: targetPdf,
        sizeKB: parseFloat((pdfStat.size / 1024).toFixed(1)),
      };
    } catch (err) {
      report.postCompileError = `Failed to finalize PDF: ${err.message}`;
    }
  }

  await rm(compileDir, { recursive: true, force: true }).catch(() => {});

  console.log(JSON.stringify(report, null, 2));
  process.exit(report.compiled ? 0 : 1);
}

main();
